---
- name: Start Traefik
  block:
    - name: Create Traefik Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ traefik_data_directory }}"
        - "{{ traefik_data_directory }}/letsencrypt"
    - name: Template Traefik traefik.toml
      template:
        src: traefik.toml
        dest: "{{ traefik_data_directory }}/traefik.toml"
      register: template_config
    - name: Template Traefik config.yml
      template:
        src: config.yml
        dest: "{{ traefik_data_directory }}/config.yml"
      register: template_provider_config
    - name: Template Traefik usersFile
      template:
        src: usersFile
        dest: "{{ traefik_data_directory }}/usersFile"
      register: template_users_file
    - name: Traefik Docker Container
      docker_container:
        name: traefik
        image: traefik:v2.4
        pull: true
        network_mode: host
        volumes:
          - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
          - "{{ traefik_data_directory }}/config.yml:/etc/traefik/config.yml:ro"
          - "{{ traefik_data_directory }}/usersFile:/etc/traefik/usersFile:ro"
          - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
          - /var/run/docker.sock:/var/run/docker.sock:ro
        env: "{{ traefik_environment_variables }}"
        restart_policy: unless-stopped
        memory: "{{ traefik_memory }}"
        recreate: "{{ template_config is changed or template_provider_config is changed }}"
  when: traefik_enabled is true
- name: Stop Traefik
  block:
    - name: Stop Traefik
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        state: absent
  when: traefik_enabled is false
