---
http:
  # region routers
  routers:
    rick:
      entryPoints:
        - websecure
      rule: Host(`rick.example.com`)
      tls:
        certResolver: letsencrypt
      service: rick
  # endregion
  # region services
  services:
    rick:
      loadBalancer:
        servers:
          - url: https://pypeaday.github.io/rick/
        passHostHeader: true
  # endregion
  middlewares:
    simple-auth:
      basicAuth:
        usersFile: /etc/traefik/usersFile
    https-redirect:
      redirectScheme:
        scheme: https
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.220.108.0/24 # wg
          - 192.168.1.0/24 # lan
          - 172.17.0.0/16 # docker
          - 172.19.0.0/16 # docker
          - 172.20.0.0/16 # docker
          - 172.22.0.0/16 # docker
    extended-whitelist:
      ipWhiteList:
        sourceRange:
          - 192.168.1.0/24 # lan
          - 172.17.0.0/16 # docker
    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
