# roles/nginx_reverse_proxy/tasks/main.yml

- name: Copy NGINX configuration template
  template:
    src: traefik.conf.j2
    dest: /etc/nginx/sites-available/traefik.conf
  notify: Restart NGINX

- name: Ensure NGINX configuration is enabled
  file:
    src: /etc/nginx/sites-available/traefik.conf
    dest: /etc/nginx/sites-enabled/traefik.conf
    state: link
  notify: Restart NGINX
