name: ☁ ️Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      # TODO: remove this
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #   with:
      #     ref: main

      - uses: actions/checkout@v1  
        continue-on-error: true
        with:
          repository: DigitalHarbor7/digital-harbor-site-generator
          ref: refs/heads/main
          token: ${{ secrets.GH_ACCESS_TOKEN }}


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Build site
        run: |
          # placeholde dhsg function that just echos command
          dhsg () {
            echo $@
          }

          # pip install git+https://github.com/DigitalHarbor7/digital-harbor-site-generator.git
          pip install -e digital-harbor-site-generator
          dhsg build --site-configs ./site-configs --output-dir _site --assets-dir --templates-dir ./templates

          # git checkout -b pages
          # git add _static
          # git commit -m "Build site"

      - name: Tag the version
        run: |
          git config remote.origin.fetch '+refs/tags/*:refs/tags/*'
          git fetch -a
          # find most recent tag
          # Get the list of git tags
          tags=$(git tag --sort=-version:refname)

          # Extract the highest number from the tags
          highest_tag=$(echo "$tags" | head -n 1 | sed 's/v//')

          # Convert the highest tag to an integer
          highest_number=$(($highest_tag))

          # Increment the highest number by 1
          next_number=$(($highest_number + 1))

          # Set a variable to the next highest number
          next_tag="v$next_number"
          echo "Next tag: $next_tag"
          # Print the next tag
          git tag $next_tag
          git push origin $next_tag
      - name: Deploy site to prd
        if: github.ref == 'refs/heads/main' 
        run: git push -u origin pages --force


      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install latest version of Wrangler
        run: npm install -g wrangler

      - name: Set deployment variables and deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          for dir in $(find _site/* -maxdepth 0 -type d -not \( -name "assets" -o -name "payment" -o -name "qr" -o -name "example" \)); do
              echo "Deploying $dir"
              PROJECT_NAME=$(basename "$dir")
              npx wrangler pages deploy "_site/$PROJECT_NAME" --project-name="$PROJECT_NAME" || echo "failed deploying $PROJECT_NAME"
          done

          # For people with multiple domains - like josh having 1man1.band and 1man1band.com, to ensure I have just the 1 index.html I'll hardcode the seperate project deployment
          echo "deploying 1man1band.com"
          npx wrangler pages deploy "_site/1man1-band" --project-name="1man1band-com"

          npx wrangler pages deploy "_site" --project-name="mydigitalharbor-com"

      # - name: Set deployment variables and deploy only if there's changes
      #   env:
      #     CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      #   run: |
      #     MAIN_COMMIT=$(git rev-parse main)
      #     CURRENT_COMMIT=${{ github.sha }}
      #     for dir in $(find _site/* -maxdepth 0 -type d -not \( -name "assets" -o -name "payment" -o -name "qr" -o -name "example" \)); do
      #       diff_output=$(git diff --name-only $MAIN_COMMIT $CURRENT_COMMIT -- $dir)
      #         echo "Deploying $dir"
      #         PROJECT_NAME=$(basename "$dir")
      #         npx wrangler pages deploy "_site/$PROJECT_NAME" --project-name="$PROJECT_NAME" else
      #       else
      #         echo "Skipping deployment for $dir as there are no file changes."
      #       fi
      #     done

      #     # For people with multiple domains - like josh having 1man1.band and 1man1band.com, to ensure I have just the 1 index.html I'll hardcode the seperate project deployment
      #     diff_output=$(git diff --name-only $MAIN_COMMIT $CURRENT_COMMIT -- _site/1man1-band)
      #     if [[ -n $diff_output ]]; then
      #       echo "deploying 1man1band.com"
      #       npx wrangler pages deploy "_site/1man1-band" --project-name="1man1band-com"
      #     else 
      #       echo "Skipping 1man1band.com"
      #     fi

      #     npx wrangler pages deploy "_site" --project-name="mydigitalharbor-com"
