name: Push pages branch in DigitalHarbor

on:
  push:
    branches:
      - main
      - develop
      # - pages
      # - pages-dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   persist-credentials: false
          # ref: main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Push to DigitalHarbor
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            target_branch="pages"
          # if on dev then add `-dev` to target_branch
          elif [[ "$GITHUB_REF" == "refs/heads/develop" ]]; then
            target_branch="pages-dev"
          fi

          git config user.email "mdh-www@github.com"
          git config user.name "github[bot]"
          # wasn't getting other branches on fetch
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch -a
          git checkout $target_branch
          echo "rebasing $target_branch on $GITHUB_REF_NAME"
          # don't reset... this gets rid of anything on develop/main... 
          # git reset $GITHUB_REF_NAME --soft
          git merge $GITHUB_REF_NAME
          git add .
          echo "making commit"
          git commit -m "Update site with Digital Harbor changes"
          # this will trigger CF Deployment with wrangler
          git push -u origin $target_branch:$target_branch --force
